### ISSUE TITLE
Get Facial feature contours

### ISSUE THREAD

**Issue by vlastelin-vlas** [tripodworks-iot/cordova-plugin-mlkit-facedetection#2]
When I have facial contour detection enabled, can I get a list of points for each detected facial feature?

**Comment by lei-xiaoming** [comment]
TEST

**Comment by lei-xiaoming** [comment]
Hell, thank you for the question.
The function for list of points for each detected facial feature was added.
released in v0.2.0.

Please see README.md for details.

**Comment by vlastelin-vlas** [comment]
@lei-xiaoming Thanks! Another question. The points are returned in one list. Are they in the same order as in the ML Kit documentation? That is, the first 36 points are the oval of the face, then 5 points are the left eyebrow (top), and so on?

**Comment by lei-xiaoming** [comment]
Hell, thank you for the question. 
released in v0.2.2 for 133 points.They should be in the same order as the ML kit documentation.
